export type AdminChangeLogEntry = {
  id: string;
  date: string;
  page: string;
  category: string;
  summary: string;
};

export const adminChangeLogEntries: AdminChangeLogEntry[] = [
  {
    id: "2026-02-16-camp-display-notable-feed-detail",
    date: "2026-02-16",
    page: "/display/camp",
    category: "Feed",
    summary: "Notable feed now shows richer activity detail per row (type, detail text, relative + clock time).",
  },
  {
    id: "2026-02-16-modifier-stack-effect-border",
    date: "2026-02-16",
    page: "Points Engine",
    category: "Modifiers",
    summary: "Avatar + effect + border modifiers now stack additively by percent delta, then apply once to points outcomes.",
  },
  {
    id: "2026-02-16-limited-events-upload-and-tabs",
    date: "2026-02-16",
    page: "/admin/custom/limited-events",
    category: "Events",
    summary: "Limited Events now has event tabs, bulk avatar upload from files (filename -> avatar name), in-page effect creation, per-event item editing, and student eligibility assignment.",
  },
  {
    id: "2026-02-16-camp-role-points-settings",
    date: "2026-02-16",
    page: "/camp/settings",
    category: "Camp Settings",
    summary: "Seller/Cleaner daily redeem points are now configurable in Camp Settings (no longer hardcoded).",
  },
  {
    id: "2026-02-16-camp-secondary-role-days",
    date: "2026-02-16",
    page: "/admin/custom/camp-display",
    category: "Roster Builder",
    summary: "Secondary role now has day chips (M/T/W/R/F/SA/SU) so redeem eligibility can be set by day.",
  },
  {
    id: "2026-02-16-camp-display-role-points-legend",
    date: "2026-02-16",
    page: "/display/camp",
    category: "Display UX",
    summary: "Camp display legend and left info rail were updated with seller/cleaner daily points and notable feed card.",
  },
  {
    id: "2026-02-16-student-avatar-picker-preview-panel",
    date: "2026-02-16",
    page: "/student/info",
    category: "Avatar UX",
    summary: "Avatar picker now has a left preview panel with Current vs Preview avatar and clear stat comparison rows.",
  },
  {
    id: "2026-02-16-student-avatar-picker-locked-preview",
    date: "2026-02-16",
    page: "/student/info",
    category: "Unlock UX",
    summary: "Locked avatars/effects/borders remain clickable for preview, show lock reasons, and appear slightly greyed out.",
  },
  {
    id: "2026-02-16-student-avatar-picker-filters",
    date: "2026-02-16",
    page: "/student/info",
    category: "Filters",
    summary: "Added picker chips for filtering/sorting (all/unlocked/locked/limited/level and sort by level/name/free points/MVP bonus).",
  },
  {
    id: "2026-02-16-student-avatar-modifier-copy",
    date: "2026-02-16",
    page: "/student/info",
    category: "Content",
    summary: "Avatar modifier text now uses full labels (Skill Pulse points per rep, Battle MVP bonus, Free points daily incl. 0).",
  },
  {
    id: "2026-02-16-student-info-responsive-scale",
    date: "2026-02-16",
    page: "/student/info",
    category: "Responsive",
    summary: "Added compact sizing rules for smaller screens so Student Info fits better without crowding.",
  },
  {
    id: "2026-02-16-student-nav-safe-gutter",
    date: "2026-02-16",
    page: "/student/*",
    category: "Layout",
    summary: "Added strict desktop left gutter on student routes so content does not overlap the left nav.",
  },
  {
    id: "2026-02-16-student-kiosk-controls",
    date: "2026-02-16",
    page: "/student/*",
    category: "Tablet",
    summary: "Added small top-left Fullscreen and Keep Awake controls on student pages; exiting fullscreen asks for confirmation.",
  },
  {
    id: "2026-02-16-taolu-classroom-scope-fix",
    date: "2026-02-16",
    page: "/api/taolu/student-summary",
    category: "Access",
    summary: "Classroom/check-in roles can now read selected student Taolu summary in Student Info (not just admin/coach).",
  },
  {
    id: "2026-02-16-camp-classroom-selected-font",
    date: "2026-02-16",
    page: "/camp/classroom",
    category: "UI",
    summary: "In Selected Students overlay, names were increased for better readability.",
  },
  {
    id: "2026-02-16-checkin-top-suggestion-actions",
    date: "2026-02-16",
    page: "/classroom/checkin",
    category: "UX",
    summary: "Top suggestions now show large name cards with Check In on the right and Redeem when available.",
  },
  {
    id: "2026-02-16-checkin-top-sticky",
    date: "2026-02-16",
    page: "/classroom/checkin",
    category: "Layout",
    summary: "Typed suggestions bar is now sticky at the top of the overlay so it stays visible above tablet keyboard.",
  },
  {
    id: "2026-02-16-admin-log-inpage-pin",
    date: "2026-02-16",
    page: "/admin workspace",
    category: "Feature",
    summary: "Feature Change Log now works in-page in admin workspace and uses the same Skill Tracker Admin PIN.",
  },
  {
    id: "2026-02-16-admin-log-timeline-duration",
    date: "2026-02-16",
    page: "/admin/changelog",
    category: "Feature",
    summary: "Added Timeline tab, time sort (newest/oldest), and duration filters (24h/7d/30d/all).",
  },
  {
    id: "2026-02-16-camp-display-star-clip",
    date: "2026-02-16",
    page: "/display/camp",
    category: "UI",
    summary: "Spotlight star strip now stays clipped inside card bounds when zooming.",
  },
  {
    id: "2026-02-16-checkin-suggestion-topbar",
    date: "2026-02-16",
    page: "/classroom/checkin",
    category: "UX",
    summary: "Typed name suggestions now show in a top horizontal bar; tapping one fills the input fast.",
  },
  {
    id: "2026-02-16-checkin-row-button-lock",
    date: "2026-02-16",
    page: "/classroom/checkin",
    category: "Layout",
    summary: "Search-row action layout now keeps Check In pinned on the right even when Daily Redeem appears.",
  },
  {
    id: "2026-02-16-admin-log-add-entry",
    date: "2026-02-16",
    page: "/admin/changelog",
    category: "Feature",
    summary: "Added persistent admin change log backend and an Add Log input on the log page (PIN-gated view).",
  },
  {
    id: "2026-02-16-camp-classroom-action-feedback",
    date: "2026-02-16",
    page: "/camp/classroom",
    category: "Action Feedback",
    summary: "Point/star/keeper/breaker actions now show a quick confirmation overlay and have anti-double-tap guard.",
  },
  {
    id: "2026-02-16-camp-classroom-card-sizing",
    date: "2026-02-16",
    page: "/camp/classroom",
    category: "Cards",
    summary: "Student cards now use larger name/points text, centered point chip, and level badge beside avatar.",
  },
  {
    id: "2026-02-16-checkin-overlay-controls",
    date: "2026-02-16",
    page: "/classroom/checkin",
    category: "UX",
    summary: "Check-in name overlay now auto-closes after 2s after a successful check-in unless someone is still interacting.",
  },
  {
    id: "2026-02-16-checkin-fullscreen-awake",
    date: "2026-02-16",
    page: "/classroom/checkin",
    category: "Tablet",
    summary: "Added top-left Fullscreen and Keep Awake buttons for station/tablet use.",
  },
  {
    id: "2026-02-16-skill-lanes-wager-fix",
    date: "2026-02-16",
    page: "/skill-tracker",
    category: "Points",
    summary: "Fixed old wager settlement logic so winners only get net win and no extra negative wager line.",
  },
  {
    id: "2026-02-16-skill-lanes-history-fix",
    date: "2026-02-16",
    page: "/skill-tracker",
    category: "History",
    summary: "Battle points chip now uses settlement snapshot before/after values instead of current live totals.",
  },
  {
    id: "2026-02-16-camp-display-scale",
    date: "2026-02-16",
    page: "/display/camp",
    category: "TV Layout",
    summary: "Camp display cards/fonts/avatar blocks were downsized so more content fits cleanly at normal zoom on TV.",
  },
  {
    id: "2026-02-16-avatar-overflow-scrollbars",
    date: "2026-02-16",
    page: "Avatar Rendering",
    category: "Visual",
    summary: "Code-based avatar effects now suppress iframe scrollbars so border/effect render looks cleaner.",
  },
  {
    id: "2026-02-16-avatar-bulk-upload-storage-fallback",
    date: "2026-02-16",
    page: "/admin/custom/media",
    category: "Avatars",
    summary: "Bulk-uploaded avatars now save cleanly even if storage_path is missing in update payload; new-avatar Add now prompts to upload/browse first.",
  },
  {
    id: "2026-02-16-challenges-category-not-null-fix",
    date: "2026-02-16",
    page: "/admin/custom/challenges",
    category: "Backend",
    summary: "Challenge save now defaults empty category to 'General' to satisfy DB not-null constraint.",
  },
  {
    id: "2026-02-16-camp-classroom-award-selection-and-labels",
    date: "2026-02-16",
    page: "/camp/classroom",
    category: "UX",
    summary: "After point awards, selected students clear automatically; selected overlay supports per-student remove; 'Given' label now shows as 'Points Awarded'.",
  },
  {
    id: "2026-02-16-camp-classroom-lite-load",
    date: "2026-02-16",
    page: "/camp/classroom",
    category: "Performance",
    summary: "Camp classroom now loads via lite roster mode, skipping heavy redeem/tally/announcement/order-merge work for much faster initial render.",
  },
  {
    id: "2026-02-16-camp-classroom-hide-top-nav",
    date: "2026-02-16",
    page: "/camp/classroom",
    category: "Layout",
    summary: "Top nav is hidden on camp classroom route for a cleaner kiosk/fullscreen workflow.",
  },
  {
    id: "2026-02-16-camp-classroom-rule-week-scaling",
    date: "2026-02-16",
    page: "/camp/classroom",
    category: "Rules",
    summary: "Rule Keeper/Breaker now follow season week scaling (5 points per week, capped at 50) instead of fixed hardcoded values.",
  },
  {
    id: "2026-02-16-spin-hide-nav-and-wheel-scale",
    date: "2026-02-16",
    page: "/spin",
    category: "Layout",
    summary: "Top nav removed on Spin and wheel area enlarged significantly (bigger canvas cap, taller panel, wider wheel region).",
  },
  {
    id: "2026-02-16-taolu-scoring-refresh",
    date: "2026-02-16",
    page: "/taolu-tracker",
    category: "Points Logic",
    summary: "Taolu scoring updated: start at 10, each deduction is -4, single-session refinement is +2 per fixed deduction; 7d/30d/3mo window refinement now uses doubled weights (+10 fixed, -10 missed, -6 new) with explicit formulas in notes/UI text.",
  },
];
